### ISSUE TITLE
Download ROM

### ISSUE THREAD

**Issue by c3r5b8** [web1n/android_device_xiaomi_elish#1]
Is there any way to download this ROM?

**Comment by web1n** [comment]
There is no uploaded rom, you can compile it yourself.

**Comment by c3r5b8** [comment]
Okay
Can you help me please?
If yes, how would you like to communicate?

**Comment by web1n** [comment]
Do you use Telegram? I can communicate with you via telegram.

**Comment by c3r5b8** [comment]
Yes, username same as here.

**Comment by web1n** [comment]
ok
